name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage                            #this is new
          python -m pip install requests
          python -m pip install pandas
          python -m pip install matplotlib
          python -m pip install sqlalchemy

      - name: Test with unittest
        run: python3 -m unittest unit-test.py
          
      - name: Check code coverage                        #new from here down
        run: |
          python3 -m coverage run -m unittest unit-test.py
          python3 -m coverage report
          python3 -m coverage html
          
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-report
           path: htmlcov
           
           